In [1]:
from numpy import *

In [3]:
a = matrix([[0.8,0.2],[0.7,0.3]])
a

matrix([[ 0.8,  0.2],
        [ 0.7,  0.3]])

In [5]:
b = a *a
b

matrix([[ 0.78,  0.22],
        [ 0.77,  0.23]])

In [7]:
b = a**10
b

matrix([[ 0.77777778,  0.22222222],
        [ 0.77777778,  0.22222222]])