In [2]:
from keras.models import Sequential
from keras.layers import  Dense,Activation
import keras
keras.__version__

'2.2.2'

In [3]:
model =Sequential([Dense(32, input_shape=(784,)),
                  Activation('relu'),Dense(10),
                  Activation('softmax')])

In [4]:
model = Sequential()
model.add(Dense(32,input_dim=784))
model.add(Activation('relu'))

In [5]:
model = Sequential()
model.add(Dense(32,input_shape=(784,)))
model = Sequential()
model.add(Dense(32,input_dim=784))

In [6]:
# For a multi-class classification problem
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# For a binary classification problem
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# For a mean squared error regression problem
model.compile(optimizer='rmsprop',
              loss='mse')

# For custom metrics
import keras.backend as K

def mean_pred(y_true, y_pred):
    return K.mean(y_pred)

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy', mean_pred])

In [7]:
model =Sequential()
model.add(Dense(32, activation='relu',input_dim=100))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

import numpy as np
data = np.random.random((1000,100))
labels = np.random.randint(2,size=(1000,1))
m = model.fit(data,labels,epochs=10,batch_size=32)

Epoch 1/10
1000/1000 [==============================] - 0s 254us/step - loss: 0.7128 - acc: 0.4940
Epoch 2/10
1000/1000 [==============================] - 0s 36us/step - loss: 0.7018 - acc: 0.5100
Epoch 3/10
1000/1000 [==============================] - 0s 34us/step - loss: 0.6973 - acc: 0.5250
Epoch 4/10
1000/1000 [==============================] - 0s 33us/step - loss: 0.6960 - acc: 0.5270
Epoch 5/10
1000/1000 [==============================] - 0s 36us/step - loss: 0.6924 - acc: 0.5090
Epoch 6/10
1000/1000 [==============================] - 0s 36us/step - loss: 0.6876 - acc: 0.5420
Epoch 7/10
1000/1000 [==============================] - 0s 34us/step - loss: 0.6814 - acc: 0.5640
Epoch 8/10
1000/1000 [==============================] - 0s 34us/step - loss: 0.6827 - acc: 0.5590
Epoch 9/10
1000/1000 [==============================] - 0s 33us/step - loss: 0.6787 - acc: 0.5800
Epoch 10/10
1000/1000 [==============================] - 0s 33us/step - loss: 0.6759 - acc: 0.5690


In [8]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=100))
model.add(Dense(10,activation='softmax'))
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])


In [8]:
import numpy as np
data =np.random.random((1000,100))
labels = np.random.randint(10,size=(1000,1))   #生成0-9之间的数据
import keras


In [9]:
one_hot_labels = keras.utils.to_categorical(labels,num_classes=10)
#print(one_hot_labels[:10])
#print(labels[:10])
#print(max(labels))

In [12]:
#model.fit(data,one_hot_labels,epochs=10,batch_size=32)

In [13]:
## 多层感知机  多分类
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation
from keras.optimizers import SGD
import numpy as np

In [14]:
x_train = np.random.random((1000,20))
y_train = keras.utils.to_categorical(np.random.randint(10,size=(1000,1)),num_classes=10)
x_test = np.random.random((100,20))
y_test = keras.utils.to_categorical(np.random.randint(10,size=(100,1)),num_classes=10)


In [15]:
model =Sequential()
model.add(Dense(64,activation='relu',input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))

sgd = SGD(lr=0.01,decay=1e-6,momentum=0.9,nesterov=True)

model.compile(loss='categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])
model.fit(x_train,y_train,epochs=20,batch_size=128)
score = model.evaluate(x_test,y_test)
print(score)

ValueError: Error when checking target: expected dense_12 to have 2 dimensions, but got array with shape (1000, 1, 10)

In [16]:
# 二分类多层感知机

import keras
from keras.models import Sequential
from keras.layers import  Dense,Dropout
import numpy as np

In [17]:
x_train = np.random.random((1000,20))
y_train = np.random.randint(2,size=(1000,1))
x_test = np.random.random((100,20))
y_test = np.random.randint(2,size=(100,1))

model =Sequential()
model.add(Dense(64,input_dim=20,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='rmsprop',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=10,batch_size=128)
score = model.evaluate(x_test,y_test,batch_size=128)
print(score)


Epoch 1/10
1000/1000 [==============================] - 1s 519us/step - loss: 0.7117 - acc: 0.5010
Epoch 2/10
1000/1000 [==============================] - 0s 18us/step - loss: 0.7035 - acc: 0.4910
Epoch 3/10
1000/1000 [==============================] - 0s 18us/step - loss: 0.7083 - acc: 0.4870
Epoch 4/10
1000/1000 [==============================] - 0s 19us/step - loss: 0.6963 - acc: 0.5110
Epoch 5/10
1000/1000 [==============================] - 0s 19us/step - loss: 0.6910 - acc: 0.5220
Epoch 6/10
1000/1000 [==============================] - 0s 19us/step - loss: 0.6987 - acc: 0.5050
Epoch 7/10
1000/1000 [==============================] - 0s 18us/step - loss: 0.6973 - acc: 0.5000
Epoch 8/10
1000/1000 [==============================] - 0s 18us/step - loss: 0.6916 - acc: 0.5290
Epoch 9/10
1000/1000 [==============================] - 0s 19us/step - loss: 0.6992 - acc: 0.5200
Epoch 10/10
100/100 [==============================] - 0s 445us/step
[0.69233191013336182, 0.49000000953674316]


In [23]:
#对数据进行切割或者填充。
def pad(data,len_v,pad_value,cut=True): 
    d_len =len(data)
    if len_v>d_len:
        data = data+[pad_value]*(len_v-d_len)  #这个地方一定要加一个 [] 即 [pad_value]
    if len_v<d_len and cut:
        data = data[:len_v]
    else:
        data = data
    return data
print(pad(a,10,'0'))
print(pad(a,4,'0'))
print(pad(a,4,'0',cut=False))  #这里三种用法需要注意不要 。


['a', 'b', 'c', 'a', 'b', 'c', '0', '0', '0', '0']
['a', 'b', 'c', 'a']
['a', 'b', 'c', 'a', 'b', 'c']


In [24]:
import time
import sys
for i in range(5):
    print(i,end=''), #这里的用法需要注意 #
    #sys.stdout.flush()
    time.sleep(2)

01234

In [129]:
d = [line.strip() for line in open("/Users/luokui/test.txt")]
#print(d)
xx =[]
yy =[]

for line in open("/Users/luokui/test.txt"):
    #print(len(line))#居然可以直接这么用啊 不能这么用 是错误的啊
    #print(line[0])
    x,y=line.rsplit(maxsplit=1) 
    #print(x,y)#注意这里的rsplit的用法 直接将后面的 label 解放出来的 。
    x = "_".join(x.split())
    xx.append(x)
    yy.append(y)
#print(xx)
#print(yy)

fr = open("/Users/luokui/test.txt")
for line in fr.readlines():
    line=line.strip()
    print(len(line))
    x,y = line.rsplit(maxsplit=1)
    x = "_".join(x.split())
    xx.append(x)
    yy.append(y)
print(xx,yy)

7
7
['a_c_d', 'e_f_g', 'a_c_d', 'e_f_g'] ['x', 'y', 'x', 'y']


In [9]:
from keras.layers import ZeroPadding1D
from keras.layers import Dense,Input
from keras.models import Model,Sequential

In [23]:
import numpy as np
d = np.arange(24).reshape((2,3,4))
ins = Input(shape=(3,4))
#model = Sequential()
#model.add(ZeroPadding1D(padding=1))
t = ZeroPadding1D(padding=(0,1))(ins)
t

<tf.Tensor 'zero_padding1d_15/Pad:0' shape=(?, 4, 4) dtype=float32>

In [54]:
import numpy as np
d = np.arange(24).reshape((2,3,4))

ins = Input(shape=(3,4))
y = ZeroPadding1D(padding=(2,1))(ins)
model = Model(ins,y)

# model.compile(optimizer='rmsprop',loss='mean_squared_error')
#print(model.fit(d)) 这里不需要使用  fit函数 ，直接使用 predict 就可以了
model.predict(d)

array([[[  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.],
        [  0.,   0.,   0.,   0.]],

       [[  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [ 12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.],
        [ 20.,  21.,  22.,  23.],
        [  0.,   0.,   0.,   0.]]], dtype=float32)

In [51]:
import numpy as np
d = np.arange(24).reshape((2,3,4))

model = Sequential()
model.add(Dense(units=4,input_shape=(3,4)))
model.add(ZeroPadding1D(padding=1))

#model.compile(optimizer='rmsprop',loss='mean_squared_error')
model.predict(d)

array([[[  0.        ,   0.        ,   0.        ,   0.        ],
        [ -4.12963104,  -2.43187332,  -2.15302944,   0.56728989],
        [-11.53649139,  -7.70167255,  -5.38438988,   1.77262115],
        [-18.94335175, -12.97147179,  -8.61574936,   2.97795248],
        [  0.        ,   0.        ,   0.        ,   0.        ]],

       [[  0.        ,   0.        ,   0.        ,   0.        ],
        [-26.3502121 , -18.24127197, -11.84710884,   4.18328381],
        [-33.75707245, -23.51107025, -15.07847023,   5.38861561],
        [-41.1639328 , -28.78086853, -18.30982971,   6.59394646],
        [  0.        ,   0.        ,   0.        ,   0.        ]]], dtype=float32)

In [9]:
import keras

In [18]:
from keras.models import Sequential
from keras.layers import  TimeDistributed,Conv2D

In [12]:
model  = Sequential()
model.add(TimeDistributed(Dense(8),input_shape=(10,16)))

In [13]:
model.output_names

['time_distributed_1']

In [16]:
model.output_shape

(None, 10, 8)

In [28]:
model = Sequential()
model.add(TimeDistributed(Conv2D(64, (3, 3)),input_shape=(10, 299, 299, 3)))

In [20]:
model.outputs

[<tf.Tensor 'time_distributed_2/Reshape_1:0' shape=(?, 10, 297, 297, 64) dtype=float32>]

In [21]:
model.output_shape

(None, 10, 297, 297, 64)

In [22]:
keras.utils.print_summary(model)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
time_distributed_2 (TimeDist (None, 10, 297, 297, 64)  1792      
Total params: 1,792
Trainable params: 1,792
Non-trainable params: 0
_________________________________________________________________


In [27]:
1792-299*3

895

In [29]:
a = np.arange(24).reshape(2,3,4)

In [39]:
b = np.array([[[1,1,1],[1,1,1],[2,2,2]],[[2,2,2],[2,2,2],[1,1,1]]])
b

array([[[1, 1, 1],
        [1, 1, 1],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [1, 1, 1]]])

In [37]:
t = keras.utils.normalize(a,axis=-1,order=2)
np.mean(t,axis=-1)

array([[0.40089186, 0.48997894, 0.49657295],
       [0.49829409, 0.4989827 , 0.49932533]])

In [48]:
t1 = keras.utils.normalize(b,axis=2,order=2)
t1

array([[[0.57735027, 0.57735027, 0.57735027],
        [0.57735027, 0.57735027, 0.57735027],
        [0.57735027, 0.57735027, 0.57735027]],

       [[0.57735027, 0.57735027, 0.57735027],
        [0.57735027, 0.57735027, 0.57735027],
        [0.57735027, 0.57735027, 0.57735027]]])

In [45]:
np.mean(t1,axis=-1)

array([[0.57735027, 0.57735027, 0.57735027],
       [0.57735027, 0.57735027, 0.57735027]])

In [55]:
keras.utils.normalize(b[0],axis=1,order=2)

array([[0.57735027, 0.57735027, 0.57735027],
       [0.57735027, 0.57735027, 0.57735027],
       [0.57735027, 0.57735027, 0.57735027]])

In [56]:
b[0]

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [58]:
np.mean(b[0],axis=)

array([1.33333333, 1.33333333, 1.33333333])